alias visual-studio='monodevelop'
alias sfiles='sudo nautilus'
alias install='sudo apt update; sudo apt install'
alias s-install='sudo snap install'
alias internet='google-chrome'
alias tweak='gnome-tweaks'
alias upgrade='sudo apt update; sudo apt upgrade'
alias full-upgrade='sudo apt update; sudo apt full-upgrade'
alias dist-upgrade='sudo apt update; sudo apt dist-upgrade'
alias purge='sudo apt purge'
alias clean-up='sudo apt autoremove'
alias ls='ls --color=auto'
alias mount='mount |column -t'
