alias visual-studio='monodevelop'
alias sfiles='sudo nautilus'
alias install='sudo apt update; sudo apt install -y'
alias sinstall='sudo snap install -y'
alias dinstal='sudo dpkg -i'
alias internet='google-chrome'
alias tweak='gnome-tweaks'
alias upgrade='sudo apt update; sudo apt upgrade -y'
alias full-upgrade='sudo apt update; sudo apt full-upgrade -y'
alias dist-upgrade='sudo apt update; sudo apt dist-upgrade -y'
alias purge='sudo apt purge -y'
alias cleanapps='sudo apt autoremove -y'
alias ls='ls --color=auto'
alias mount='mount |column -t'
alias cleancfg='./.clean.sh'
alias reinstall='sudo apt reinstall -y'
